### ISSUE TITLE
Reverse motor direction not working

### ISSUE THREAD

**Issue by alros100** [brownrb/myFP2EFirmware#20] opened 2021-01-01 13:27 UTC
ESP8266
135 version firmware (last one prior to move to github)
myespfp2esp version 2.0.3.25
also ascom driver

motor reverse direction checkbox does not appear to function.

same rig works with arduino nano 

thanks
Al

**Comment by brownrb** [comment] 2021-01-02 00:40
The Windows app myFP2ESP definately seems to be sending the correct commands to reverse the motor direction.

It looks like it is a firmware issue. I confirtm reverse direction does not work:
data_per.jsn is clearly being updated with new reverse direction state:
Web server is clearly reporting new reverse direction state:
Motor keeps rotating in same direction as before the change.
Tested and confirmed not working with v129 and latest version Jan 01-2021

**Comment by brownrb** [comment] 2021-01-02 02:58
Am working on fix and other updates

**Comment by brownrb** [comment] 2021-01-02 05:05
Resolved in branch 134 update - now merged into Master

**Closed by brownrb** 2021-01-02 05:05 UTC
